name: Upload Release Assets
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - '!v*-test' # Exclude above tags ending with "-test"
jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build Userscript
        shell: bash
        run: cat script.meta.js src/script.js > script.user.js
      - name: Tag Name
        id: tagname
        shell: bash
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tagname.outputs.TAG }}
          name: Release ${{ steps.tagname.outputs.TAG }}
          artifact: script.user.js
