name: New release from tag

on:
  push:
    tags: 'v*'

defaults:
  run:
    shell: bash

jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Version check
      run: |
        echo "::group::Version check"
        echo "Github tag: $GITHUB_REF_NAME"
        echo "Version tag: $(awk '/@version/ {printf "v%s",$3}' script.meta.js)"
        [[ $(awk '/@version/ {printf "v%s",$3}' script.meta.js) == $GITHUB_REF_NAME ]]
        echo "Resource tag: $(awk '/@resource/ {split($4,F,"/"); print F[8]}' script.meta.js)"
        [[ $(awk '/@resource/ {split($4,F,"/"); print F[8]}' script.meta.js) == $GITHUB_REF_NAME ]]
        echo "::endgroup::"
    
    - name: Build userscript
      run: |
        echo "::group::Building userscript..."
        cat script.meta.js src/script.js > script.user.js
        readlink -f script.user.js
        echo "::endgroup::"

    - name: Build JSON bundle
      run: |
        echo "::group::Building JSON bundle..."
        shopt -s extglob
        jq -Rn -f .github/filter.jq src/!(script.js) > content.json
        readlink -f content.json
        echo "::endgroup::"

    - name: Create release draft
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ github.ref_name }}
        draft: true
        prerelease: ${{ contains(github.ref_name, 'dev') }}
        artifacts: "script.user.js,content.json"
        artifactErrorsFailBuild: true        
