name: New release from tag
on:
  push:
    branches: [master]
    tags: 'test*'
defaults:
  run:
    shell: bash
jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Userscript
      id: buildtag
      run: |
        echo "Building userscript"
        cat script.meta.js src/script.js > script.user.js
        echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.buildtag.outputs.TAG }}
        release_name: Release ${{ steps.buildtag.outputs.TAG }}
        draft: true
        prerelease: true
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./script.user.js
        asset_name: script_${{ steps.buildtag.outputs.TAG }}.user.js
        asset_content_type: application/javascript
